"""test

Revision ID: 63a90867d232
Revises: 
Create Date: 2020-10-25 21:51:49.864770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a90867d232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('old_password', sa.String(length=100), nullable=True),
    sa.Column('term_condi', sa.Integer(), nullable=True),
    sa.Column('wrong_login_attempt', sa.DateTime(), nullable=True),
    sa.Column('today_login_attempt', sa.DateTime(), nullable=True),
    sa.Column('is_now_login', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attrition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id_state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('civil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_name', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name_inst', sa.String(length=300), nullable=False),
    sa.Column('field', sa.Integer(), nullable=True),
    sa.Column('from_year', sa.String(length=300), nullable=False),
    sa.Column('to_year', sa.String(length=300), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('ruc', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('fax', sa.String(length=20), nullable=False),
    sa.Column('type_job', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fax'),
    sa.UniqueConstraint('id_account'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=False),
    sa.Column('name_inst', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('job_level', sa.Integer(), nullable=True),
    sa.Column('from_year', sa.String(length=100), nullable=True),
    sa.Column('to_year', sa.String(length=100), nullable=True),
    sa.Column('buss_travel', sa.Integer(), nullable=True),
    sa.Column('distan_home', sa.Float(), nullable=True),
    sa.Column('hour_rate', sa.Float(), nullable=True),
    sa.Column('job_role', sa.Integer(), nullable=True),
    sa.Column('job_sati', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('over_time', sa.Integer(), nullable=True),
    sa.Column('work_bal_life', sa.Integer(), nullable=True),
    sa.Column('job_invol', sa.Integer(), nullable=True),
    sa.Column('attrition', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_enterprise', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('from_date', sa.String(length=30), nullable=False),
    sa.Column('to_date', sa.String(length=300), nullable=False),
    sa.Column('job_role', sa.Integer(), nullable=False),
    sa.Column('type_job', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_trans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_publication', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('type_doc', sa.Integer(), nullable=False),
    sa.Column('num_doc', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('id_state', sa.Integer(), nullable=False),
    sa.Column('id_city', sa.Integer(), nullable=False),
    sa.Column('id_civil_status', sa.Integer(), nullable=False),
    sa.Column('id_provider', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_account'),
    sa.UniqueConstraint('num_doc'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('states')
    op.drop_table('publication_trans')
    op.drop_table('publication')
    op.drop_table('level')
    op.drop_table('job_role')
    op.drop_table('job_level')
    op.drop_table('job')
    op.drop_table('field')
    op.drop_table('enterprise')
    op.drop_table('education')
    op.drop_table('document')
    op.drop_table('department')
    op.drop_table('countries')
    op.drop_table('civil')
    op.drop_table('cities')
    op.drop_table('blacklist_tokens')
    op.drop_table('attrition')
    op.drop_table('account')
    # ### end Alembic commands ###
